name: Build Swift for a given distribution
description: This wraps all the functionality of other actions to build Swift for a given distribution
inputs:
  swift-tag:
    description: The Swift tag version that is being built
    required: true
  swift-target-arch:
    description: The target architecture to build Swift for (e.g., armv6 or armv7)
    required: true
  swift-workspace-cache:
    description: The name of the Swift workspace directory to restore
    required: true
  distribution:
    description: The name of the distribution to build for
    required: true
  builder-tag:
    description: Tag of the swift-builder container to use to build Swift
    required: true
runs:
  using: "composite"
  steps:
  - name: Restore Workspace Dir
    if: ${{ inputs.swift-workspace-cache != '' }}
    uses: actions/cache/restore@v4
    with:
      key: ${{ inputs.swift-workspace-cache }}
      path: downloads
      fail-on-cache-miss: true
  - uses: ./.github/actions/build-with-sysroot
    name: Build Swift + SDK using Sysroot
    with:
      swift-tag: ${{ inputs.swift-tag }}
      sysroot-name: sysroot-${{ inputs.distribution }}
      swift-target-arch: ${{ inputs.swift-target-arch }}
      distribution: ${{ inputs.distribution }}
      builder-tag: ${{ inputs.builder-tag }}
