stages:
  - build

build-swift-armv7:
  image: colemancda/swift-armv7
  stage: build
  script:
    - export SRC_ROOT=$(pwd)
    - ./build.sh
  artifacts:
    paths: 
      - ./build/swift-armv7.tar.gz
  tags:
    - bastion-c5d.9xl
