#!/bin/bash
set -e
source swift-define

BUILD_DESCRIPTION="Dispatch"
if [ $STATIC_BUILD ]; then
    BUILD_DESCRIPTION="${BUILD_DESCRIPTION} Static"
    LIBDISPATCH_BUILDDIR=$LIBDISPATCH_STATIC_BUILDDIR
    LIBDISPATCH_INSTALL_PREFIX=$LIBDISPATCH_STATIC_INSTALL_PREFIX
    BUILD_SHARED_LIBS=OFF
else
    BUILD_SHARED_LIBS=ON
fi

echo "Create ${BUILD_DESCRIPTION} build folder ${SWIFT_BUILDDIR}"
mkdir -p $LIBDISPATCH_BUILDDIR
rm -rf $LIBDISPATCH_INSTALL_PREFIX
mkdir -p $LIBDISPATCH_INSTALL_PREFIX

echo "Configure ${BUILD_DESCRIPTION}"
rm -rf $LIBDISPATCH_BUILDDIR/CMakeCache.txt
cmake -S $LIBDISPATCH_SRCDIR -B $LIBDISPATCH_BUILDDIR -G Ninja \
        -DCMAKE_INSTALL_PREFIX=${LIBDISPATCH_INSTALL_PREFIX} \
        -DBUILD_TESTING=OFF \
        -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} \
        -DCMAKE_BUILD_TYPE=${SWIFT_BUILD_CONFIGURATION} \
        -DCMAKE_TOOLCHAIN_FILE="${CROSS_TOOLCHAIN_FILE}" \
        -DENABLE_SWIFT=YES \
        -DCMAKE_Swift_FLAGS="${SWIFTC_FLAGS}" \
        -DCMAKE_Swift_FLAGS_DEBUG="" \
        -DCMAKE_Swift_FLAGS_RELEASE="" \
        -DCMAKE_Swift_FLAGS_RELWITHDEBINFO="" \

echo "Build ${BUILD_DESCRIPTION}"
(cd $LIBDISPATCH_BUILDDIR && ninja)

echo "Install ${BUILD_DESCRIPTION}"
(cd $LIBDISPATCH_BUILDDIR && ninja install)
