name: Checkout Swift sources
description: Checks out the provided Swift version and performs a cache/restore
inputs:
  swift-tag:
    description: The Swift tag version that is being built
    required: true
  swift-workspace-cache:
    description: The name of the Swift workspace directory to cache/restore
    required: true
runs:
  using: "composite"
  steps:
  - name: Restore Workspace Dir
    id: restore-workspace
    uses: actions/cache/restore@v4
    with:
      key: ${{ inputs.swift-workspace-cache }}
      path: downloads
  - name: Checkout Sources
    shell: bash
    run: SWIFT_VERSION=${{ inputs.swift-tag }} ./fetch-sources.sh
  - uses: actions/cache/save@v4
    with:
      key: ${{ inputs.swift-workspace-cache }}
      path: downloads
