name: Build Linux cross-compiling SDK for Swift armv7
description: Creates a cross-compiling SDK (old style) for Swift armv7
inputs:
  swift-tag:
    description: The Swift tag version that is being built
    required: true
  sysroot-name:
    description: The name of the sysroot to use to build Swift
    required: true
  distribution:
    description: The distribution to build Swift for
    required: true
  builder-tag:
    description: Tag of the swift-builder container to use to build Swift
    required: true
runs:
  using: "composite"
  steps:
    - name: Build SDK for Linux
      shell: bash
      run: |
        INSTALLABLE_SDK_PACKAGE=$(pwd)/${{ inputs.swift-tag }}-${{ inputs.distribution }}-armv7-sdk.tar.gz SYSROOT=${{ inputs.sysroot-name }} \
          ./build-linux-cross-sdk.sh ${{ inputs.swift-tag }} ${{ inputs.distribution }}
    - name: Test SDK for Linux
      shell: bash
      env:
        SDK_NAME: ${{ inputs.swift-tag }}-${{ inputs.distribution }}-armv7
      run: |
        docker run --rm --user runner --workdir ${{ github.workspace }} -v $HOME:$HOME -v ${{ github.workspace }}/artifacts:/opt \
          xtremekforever/swift-builder:${{ inputs.builder-tag }} \
          swift build -c release \
            --package-path swift-hello \
            --destination /opt/${{ env.SDK_NAME }}/${{ inputs.distribution }}.json \
            -Xswiftc -cxx-interoperability-mode=default \
            -Xswiftc -enable-testing
        - uses: actions/upload-artifact@v4
    - name: Publish
      with:
        name: ${{ inputs.swift-tag }}-${{ inputs.distribution }}-armv7-sdk
        path: |
          ${{ inputs.swift-tag }}*-armv7-sdk.tar.gz
