name: Build Swift 5.9.2

on:
  push:
    branches: [ "main", "feature/swift-5.9.2**" ]
  pull_request:
    branches: [ "main" ]
  
env:
  SWIFT_TAG: swift-5.9.2-RELEASE
  SWIFT_WORKSPACE_CACHE: swift-5.9.2-workspace
  SWIFT_BUILDER_TAG: 5.9.2-gh-runner

jobs:
  fetch-sources:
    name: Fetch Swift Sources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/checkout-swift
      name: Restore or Checkout
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        swift-workspace-cache: ${{ env.SWIFT_WORKSPACE_CACHE }}

  debian-bookworm:
    name: Build for Debian Bookworm
    runs-on: ubuntu-latest
    needs: [fetch-sources]
    env:
      SYSROOT_ID: sysroot-${{ github.job }}
      SYSROOT_NAME: sysroot-${{ github.job }}-armv7
      CPP_VERSION: 12
      DISTRIBUTION: ${{ github.job }}
    steps:
    - uses: actions/checkout@v4
    - name: Restore Workspace Dir
      uses: actions/cache/restore@v4
      with:
        key: ${{ env.SWIFT_WORKSPACE_CACHE }}
        path: downloads
        fail-on-cache-miss: true
    - uses: ./.github/actions/build-sysroot
      name: Restore or Build Sysroot
      with:
        sysroot-id: ${{ env.SYSROOT_ID }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        distribution: ${{ env.DISTRIBUTION }}
    - uses: ./.github/actions/build-swift
      name: Build Swift
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        cpp-version: ${{ env.CPP_VERSION }}
        distribution: ${{ env.DISTRIBUTION }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}
    - uses: ./.github/actions/build-sdk
      name: Build SDK
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        distribution: ${{ env.DISTRIBUTION }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}

  ubuntu-jammy:
    name: Build for Ubuntu Jammy
    runs-on: ubuntu-latest
    needs: [fetch-sources]
    env:
      SYSROOT_ID: sysroot-${{ github.job }}
      SYSROOT_NAME: sysroot-${{ github.job }}-armv7
      CPP_VERSION: 10
      DISTRIBUTION: ${{ github.job }}
    steps:
    - uses: actions/checkout@v4
    - name: Restore Workspace Dir
      uses: actions/cache/restore@v4
      with:
        key: ${{ env.SWIFT_WORKSPACE_CACHE }}
        path: downloads
        fail-on-cache-miss: true
    - uses: ./.github/actions/build-sysroot
      name: Restore or Build Sysroot
      with:
        sysroot-id: ${{ env.SYSROOT_ID }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        distribution: ${{ env.DISTRIBUTION }}
    - uses: ./.github/actions/build-swift
      name: Build Swift
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        cpp-version: ${{ env.CPP_VERSION }}
        distribution: ${{ env.DISTRIBUTION }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}
    - uses: ./.github/actions/build-sdk
      name: Build SDK
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        distribution: ${{ env.DISTRIBUTION }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}

  ubuntu-noble:
    name: Build for Ubuntu Noble
    runs-on: ubuntu-latest
    needs: [fetch-sources]
    env:
      SYSROOT_ID: sysroot-${{ github.job }}
      SYSROOT_NAME: sysroot-${{ github.job }}-armv7
      CPP_VERSION: 13
      DISTRIBUTION: ${{ github.job }}
    steps:
    - uses: actions/checkout@v4
    - name: Restore Workspace Dir
      uses: actions/cache/restore@v4
      with:
        key: ${{ env.SWIFT_WORKSPACE_CACHE }}
        path: downloads
        fail-on-cache-miss: true
    - uses: ./.github/actions/build-sysroot
      name: Restore or Build Sysroot
      with:
        sysroot-id: ${{ env.SYSROOT_ID }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        distribution: ${{ env.DISTRIBUTION }}
    - uses: ./.github/actions/build-swift
      name: Build Swift
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        cpp-version: ${{ env.CPP_VERSION }}
        distribution: ${{ env.DISTRIBUTION }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}
    - uses: ./.github/actions/build-sdk
      name: Build SDK
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        distribution: ${{ env.DISTRIBUTION }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}
