name: Build Swift
on: [push]
jobs:

  build-swift-armv7:
    name: Build Swift
    runs-on: ubuntu-20.04
    container: colemancda/swift-armv7
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Swift Version
      run: swift --version
    - name: Download LLVM
      run: |
        export SRC_ROOT=$GITHUB_WORKSPACE
        export LLVM_INSTALL_PREFIX=$SRC_ROOT/build/llvm-install
        mkdir -p $LLVM_INSTALL_PREFIX
        cd $LLVM_INSTALL_PREFIX
        wget -q https://github.com/colemancda/swift-armv7/releases/download/0.6.0/llvm-install.tar.gz
        tar -xf llvm-install.tar.gz
        rm -rf llvm-install.tar.gz
    - name: Build
      run: |
        export SRC_ROOT=$GITHUB_WORKSPACE
        ./build.sh
    - name: Archive Swift Build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: swift-armv7
        path: ./build/swift-armv7.tar.gz