name: Build Swift 5.9.2

on:
  push:
    branches: [ "main", "feature/swift-5.9.2**" ]
  pull_request:
    branches: [ "main" ]
  
env:
  SWIFT_TAG: swift-5.9.2-RELEASE
  SWIFT_WORKSPACE_CACHE: swift-5.9.2-workspace
  SWIFT_BUILDER_TAG: 5.9.2-gh-runner

jobs:
  fetch-sources:
    name: Fetch Swift Sources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/checkout-swift
      name: Restore or Checkout
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        swift-workspace-cache: ${{ env.SWIFT_WORKSPACE_CACHE }}

  debian-bookworm:
    name: Build for Debian Bookworm
    runs-on: ubuntu-latest
    needs: [fetch-sources]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-for-distribution
      name: Build & Publish Swift for Distribution
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        swift-workspace-cache: ${{ env.SWIFT_WORKSPACE_CACHE }}
        distribution: ${{ github.job }}
        cpp-version: 12
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}

  ubuntu-jammy:
    name: Build for Ubuntu Jammy
    runs-on: ubuntu-latest
    needs: [fetch-sources]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-for-distribution
      name: Build & Publish Swift for Distribution
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        swift-workspace-cache: ${{ env.SWIFT_WORKSPACE_CACHE }}
        distribution: ${{ github.job }}
        cpp-version: 10
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}
