# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build Swift 6.0.2

on:
  push:
    branches: [ "feature/swift-6.0**" ]
  pull_request:
    branches: [ "main" ]
  
env:
  SWIFT_TAG: swift-6.0.2-RELEASE
  SWIFT_WORKSPACE_CACHE: swift-6.0.2-workspace
  SWIFT_BUILDER_TAG: 6.0.2-gh-runner

jobs:
  fetch-sources:
    name: Fetch Swift Sources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Workspace Dir
      id: cache-workspace
      uses: actions/cache@v4
      with:
        key: ${{ env.SWIFT_WORKSPACE_CACHE }}
        path: downloads
        lookup-only: true
    - if: ${{ steps.cache-workspace.outputs.cache-hit != 'true' }}
      name: Checkout Sources
      run: SWIFT_VERSION=${{ env.SWIFT_TAG }} ./fetch-sources.sh

  debian-bookworm:
    name: Build for Debian Bookworm
    runs-on: ubuntu-latest
    needs: [fetch-sources]
    env:
      SYSROOT_ID: sysroot-${{ github.job }}
      SYSROOT_NAME: sysroot-${{ github.job }}-armv7
      CPP_VERSION: 12
      DISTRIBUTION: ${{ github.job }}
    steps:
    - uses: actions/checkout@v4
    - name: Restore Workspace Dir
      uses: actions/cache/restore@v4
      with:
        key: ${{ env.SWIFT_WORKSPACE_CACHE }}
        path: downloads
        fail-on-cache-miss: true
    - uses: ./.github/actions/build-sysroot
      name: Restore or Build Sysroot
      with:
        sysroot-id: ${{ env.SYSROOT_ID }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        distribution: ${{ env.DISTRIBUTION }}
    - uses: ./.github/actions/build-swift
      name: Build Swift
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        cpp-version: ${{ env.CPP_VERSION }}
        distribution: ${{ env.DISTRIBUTION }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}
    - uses: ./.github/actions/build-sdk
      name: Build SDK
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        distribution: ${{ env.DISTRIBUTION }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}

  ubuntu-jammy:
    name: Build for Ubuntu Jammy
    runs-on: ubuntu-latest
    needs: [fetch-sources]
    env:
      SYSROOT_ID: sysroot-${{ github.job }}
      SYSROOT_NAME: sysroot-${{ github.job }}-armv7
      CPP_VERSION: 10
      DISTRIBUTION: ${{ github.job }}
    steps:
    - uses: actions/checkout@v4
    - name: Restore Workspace Dir
      uses: actions/cache/restore@v4
      with:
        key: ${{ env.SWIFT_WORKSPACE_CACHE }}
        path: downloads
        fail-on-cache-miss: true
    - uses: ./.github/actions/build-sysroot
      name: Restore or Build Sysroot
      with:
        sysroot-id: ${{ env.SYSROOT_ID }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        distribution: ${{ env.DISTRIBUTION }}
    - uses: ./.github/actions/build-swift
      name: Build Swift
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        cpp-version: ${{ env.CPP_VERSION }}
        distribution: ${{ env.DISTRIBUTION }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}
    - uses: ./.github/actions/build-sdk
      name: Build SDK
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        distribution: ${{ env.DISTRIBUTION }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}

  ubuntu-noble:
    name: Build for Ubuntu Noble
    runs-on: ubuntu-latest
    needs: [fetch-sources]
    env:
      SYSROOT_ID: sysroot-${{ github.job }}
      SYSROOT_NAME: sysroot-${{ github.job }}-armv7
      CPP_VERSION: 13
      DISTRIBUTION: ${{ github.job }}
    steps:
    - uses: actions/checkout@v4
    - name: Restore Workspace Dir
      uses: actions/cache/restore@v4
      with:
        key: ${{ env.SWIFT_WORKSPACE_CACHE }}
        path: downloads
        fail-on-cache-miss: true
    - uses: ./.github/actions/build-sysroot
      name: Restore or Build Sysroot
      with:
        sysroot-id: ${{ env.SYSROOT_ID }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        distribution: ${{ env.DISTRIBUTION }}
    - uses: ./.github/actions/build-swift
      name: Build Swift
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        cpp-version: ${{ env.CPP_VERSION }}
        distribution: ${{ env.DISTRIBUTION }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}
    - uses: ./.github/actions/build-sdk
      name: Build SDK
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        sysroot-name: ${{ env.SYSROOT_NAME }}
        distribution: ${{ env.DISTRIBUTION }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}
