name: Build Swift Latest

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

env:
  SWIFT_TAG: swift-6.0.2-RELEASE
  SWIFT_WORKSPACE_CACHE: swift-6.0.2-workspace
  SWIFT_BUILDER_TAG: 6.0.2-gh-runner

jobs:
  fetch-sources:
    name: Fetch Swift Sources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/checkout-swift
      name: Restore or Checkout
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        swift-workspace-cache: ${{ env.SWIFT_WORKSPACE_CACHE }}

  ubuntu-noble:
      name: Build for Ubuntu Noble
      runs-on: ubuntu-latest
      needs: [fetch-sources]
      steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-for-distribution
        name: Build & Publish Swift for Distribution
        with:
          swift-tag: ${{ env.SWIFT_TAG }}
          swift-workspace-cache: ${{ env.SWIFT_WORKSPACE_CACHE }}
          distribution: ${{ github.job }}
          builder-tag: ${{ env.SWIFT_BUILDER_TAG }}
