# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build Swift 5.10.1

on:
  push:
    branches: [ "main", "feature/swift-5.10.1**" ]
  pull_request:
    branches: [ "main" ]
  
env:
  SWIFT_TAG: swift-5.10.1-RELEASE
  SWIFT_WORKSPACE_CACHE: swift-5.10.1-workspace
  SWIFT_BUILDER_TAG: 5.10.1-gh-runner

jobs:
  fetch-sources:
    name: Fetch Swift Sources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/checkout-swift
      name: Restore or Checkout
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        swift-workspace-cache: ${{ env.SWIFT_WORKSPACE_CACHE }}

  debian-bullseye:
    name: Build for Debian Bullseye
    runs-on: ubuntu-latest
    needs: [fetch-sources]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-for-distribution
      name: Build & Publish Swift for Distribution
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        swift-workspace-cache: ${{ env.SWIFT_WORKSPACE_CACHE }}
        distribution: ${{ github.job }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}

  debian-bookworm:
    name: Build for Debian Bookworm
    runs-on: ubuntu-latest
    needs: [fetch-sources]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-for-distribution
      name: Build & Publish Swift for Distribution
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        swift-workspace-cache: ${{ env.SWIFT_WORKSPACE_CACHE }}
        distribution: ${{ github.job }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}

  ubuntu-focal:
    name: Build for Ubuntu Focal
    runs-on: ubuntu-latest
    needs: [fetch-sources]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-for-distribution
      name: Build & Publish Swift for Distribution
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        swift-workspace-cache: ${{ env.SWIFT_WORKSPACE_CACHE }}
        distribution: ${{ github.job }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}

  ubuntu-jammy:
    name: Build for Ubuntu Jammy
    runs-on: ubuntu-latest
    needs: [fetch-sources]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-for-distribution
      name: Build & Publish Swift for Distribution
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        swift-workspace-cache: ${{ env.SWIFT_WORKSPACE_CACHE }}
        distribution: ${{ github.job }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}

  ubuntu-noble:
    name: Build for Ubuntu Noble
    runs-on: ubuntu-latest
    needs: [fetch-sources]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-for-distribution
      name: Build & Publish Swift for Distribution
      with:
        swift-tag: ${{ env.SWIFT_TAG }}
        swift-workspace-cache: ${{ env.SWIFT_WORKSPACE_CACHE }}
        distribution: ${{ github.job }}
        builder-tag: ${{ env.SWIFT_BUILDER_TAG }}
